### ISSUE TITLE
Compilation on windows

### ISSUE THREAD

**Issue by Borwe** [mattwparas/helix#12]
![image](https://github.com/user-attachments/assets/190989c6-7c85-4353-9469-89dea520b4d9)
I get this error when compiling on windows, removing that line with a `#[cfg(not(target_os = "windows"))]` on that rustix line seems to solve the compile issue.

**Comment by mattwparas** [comment]
Sorry about that. Looks like it was just an accidental import from the lsp. It should be removed now

**Comment by Borwe** [comment]
Works.
